// Mock data for development and testing
// This simulates the data structure that will come from the Django backend

export const mockUsers = {
  athlete: {
    id: 1,
    nome: "João Silva",
    name: "João Silva",
    email: "atleta@email.com",
    tipo: "atleta",
    data_nascimento: "1997-03-15",
    peso: 75,
    altura: 1.78,
    frequencia_cardiaca_repouso: 60,
    frequencia_cardiaca_maxima: 190,
    treinador_id: 2,
    data_criacao: "2024-01-15T10:00:00Z",
  },
  coach: {
    id: 2,
    nome: "Maria Santos",
    name: "Maria Santos",
    email: "treinador@email.com",
    tipo: "treinador",
    cref: "123456-G/SP",
    especialidade: "Treinamento de Força e Condicionamento",
    data_criacao: "2023-06-10T08:00:00Z",
  },
}

export const mockAthletes = [
  {
    id: 1,
    nome: "João Silva",
    name: "João Silva",
    email: "joao.silva@email.com",
    data_nascimento: "1997-03-15",
    age: 27,
    peso: 75,
    altura: 1.78,
    frequencia_cardiaca_repouso: 60,
    hrRep: 60,
    ultimaESR: 7,
    esr: 7,
    ultimaAvaliacao: "2025-01-20",
    status: "ativo",
    adherence: 85,
  },
  {
    id: 3,
    nome: "Ana Costa",
    name: "Ana Costa",
    email: "ana.costa@email.com",
    data_nascimento: "1995-07-22",
    age: 29,
    peso: 62,
    altura: 1.65,
    frequencia_cardiaca_repouso: 58,
    hrRep: 58,
    ultimaESR: 8,
    esr: 8,
    ultimaAvaliacao: "2025-01-19",
    status: "ativo",
    adherence: 92,
  },
  {
    id: 4,
    nome: "Pedro Oliveira",
    name: "Pedro Oliveira",
    email: "pedro.oliveira@email.com",
    data_nascimento: "1999-11-08",
    age: 25,
    peso: 82,
    altura: 1.85,
    frequencia_cardiaca_repouso: 62,
    hrRep: 62,
    ultimaESR: 6,
    esr: 6,
    ultimaAvaliacao: "2025-01-21",
    status: "ativo",
    adherence: 78,
  },
  {
    id: 5,
    nome: "Carla Mendes",
    name: "Carla Mendes",
    email: "carla.mendes@email.com",
    data_nascimento: "1998-04-12",
    age: 26,
    peso: 58,
    altura: 1.62,
    frequencia_cardiaca_repouso: 55,
    hrRep: 55,
    ultimaESR: 3,
    esr: 3,
    ultimaAvaliacao: "2025-01-21",
    status: "ativo",
    adherence: 65,
  },
]

export const mockTrainingPlans = [
  {
    id: 1,
    nome: "Plano de Força - Janeiro",
    descricao: "Desenvolvimento de força muscular com foco em membros superiores e inferiores",
    data_inicio: "2025-01-01",
    data_fim: "2025-01-31",
    atleta_id: 1,
    treinador_id: 2,
    status: "ativo",
    sessoes: [
      {
        id: 1,
        nome: "Treino de Força Superior",
        title: "Treino de Força Superior",
        zona_alvo: "Zona 4 - Anaeróbica",
        zone: 4,
        tipo: "Força",
        intensidade: "Alta",
        duracao: 60,
        data: "2025-01-20",
        hora: "14:00",
        timeLabel: "14:00",
        dayLabel: "Hoje",
        status: "concluido",
        fc_media: 145,
        descricao:
          "Treino focado em desenvolvimento de força muscular com exercícios compostos. Inclui agachamento, supino e levantamento terra.",
        observacoes: "Excelente execução dos movimentos. Manter a progressão de carga nas próximas sessões.",
        exercicios: [
          { nome: "Supino Reto", series: 4, repeticoes: 8, carga: 80 },
          { nome: "Desenvolvimento", series: 4, repeticoes: 10, carga: 40 },
          { nome: "Remada Curvada", series: 4, repeticoes: 10, carga: 60 },
        ],
      },
      {
        id: 2,
        nome: "Treino Aeróbico",
        title: "Treino Aeróbico",
        zona_alvo: "Zona 2 - Aeróbica",
        zone: 2,
        tipo: "Cardio",
        intensidade: "Moderada",
        duracao: 45,
        data: "2025-01-22",
        hora: "09:00",
        timeLabel: "09:00",
        dayLabel: "Amanhã",
        status: "agendado",
        fc_media: 130,
        descricao: "Treino aeróbico de intensidade moderada para melhorar a capacidade cardiovascular.",
        observacoes: "Manter ritmo constante durante toda a sessão. Hidratação é fundamental.",
        exercicios: [
          { nome: "Corrida", duracao: 30, ritmo: "Moderado" },
          { nome: "Bike", duracao: 15, ritmo: "Leve" },
        ],
      },
      {
        id: 3,
        nome: "Recuperação Ativa",
        title: "Recuperação Ativa",
        zona_alvo: "Zona 1 - Recuperação",
        zone: 1,
        tipo: "Recuperação",
        intensidade: "Leve",
        duracao: 30,
        data: "2025-01-23",
        hora: "16:00",
        timeLabel: "16:00",
        dayLabel: "Qua",
        status: "agendado",
        fc_media: 110,
        descricao:
          "Sessão de recuperação ativa para promover a circulação sanguínea e auxiliar na recuperação muscular.",
        observacoes: "Foco em movimentos suaves e alongamentos. Não force.",
        exercicios: [
          { nome: "Caminhada", duracao: 20, ritmo: "Leve" },
          { nome: "Alongamento", duracao: 10 },
        ],
      },
      {
        id: 4,
        nome: "Treino Intervalado",
        title: "Treino Intervalado",
        zona_alvo: "Zona 5 - VO2 Max",
        zone: 5,
        tipo: "HIIT",
        intensidade: "Muito Alta",
        duracao: 30,
        data: "2025-01-24",
        hora: "07:00",
        timeLabel: "07:00",
        dayLabel: "Qui",
        status: "agendado",
        fc_media: 175,
        descricao: "Treino intervalado de alta intensidade para melhorar o VO2 máximo e capacidade anaeróbica.",
        observacoes: "Aquecimento adequado é essencial. Respeite os intervalos de descanso.",
        exercicios: [
          { nome: "Sprint", series: 8, duracao: 30, descanso: 90 },
          { nome: "Burpees", series: 4, repeticoes: 15 },
        ],
      },
    ],
  },
  {
    id: 2,
    nome: "Condicionamento Aeróbico",
    descricao: "Melhoria da capacidade cardiovascular",
    data_inicio: "2025-01-15",
    data_fim: "2025-02-15",
    atleta_id: 1,
    treinador_id: 2,
    status: "ativo",
    sessoes: [
      {
        id: 5,
        nome: "Corrida Longa",
        title: "Corrida Longa",
        zona_alvo: "Zona 2 - Aeróbica",
        zone: 2,
        tipo: "Cardio",
        intensidade: "Moderada",
        duracao: 60,
        data: "2025-01-25",
        hora: "06:30",
        timeLabel: "06:30",
        dayLabel: "Sex",
        status: "agendado",
        fc_media: 135,
        descricao: "Corrida de longa duração em ritmo confortável para desenvolver base aeróbica.",
        observacoes: "Mantenha conversação durante a corrida. Se não conseguir falar, diminua o ritmo.",
        exercicios: [{ nome: "Corrida Contínua", duracao: 60, ritmo: "Confortável" }],
      },
    ],
  },
]

export const mockESRRecords = [
  {
    id: 1,
    tipo: "diario",
    valor: 7,
    data: "2025-01-20T08:00:00Z",
    atleta_id: 1,
    observacoes: "Boa recuperação após treino de ontem",
  },
  {
    id: 2,
    tipo: "pre",
    valor: 8,
    data: "2025-01-19T13:45:00Z",
    atleta_id: 1,
    observacoes: "Pronto para treinar",
  },
  {
    id: 3,
    tipo: "post",
    valor: 4,
    data: "2025-01-19T15:30:00Z",
    atleta_id: 1,
    observacoes: "Treino intenso, fadiga moderada",
  },
  {
    id: 4,
    tipo: "diario",
    valor: 9,
    data: "2025-01-18T08:00:00Z",
    atleta_id: 1,
    observacoes: "Excelente recuperação",
  },
  {
    id: 5,
    tipo: "diario",
    valor: 6,
    data: "2025-01-17T08:00:00Z",
    atleta_id: 1,
    observacoes: "Leve fadiga muscular",
  },
  {
    id: 6,
    tipo: "diario",
    valor: 8,
    data: "2025-01-16T08:00:00Z",
    atleta_id: 1,
    observacoes: "Recuperado e motivado",
  },
  {
    id: 7,
    tipo: "diario",
    valor: 10,
    data: "2025-01-15T08:00:00Z",
    atleta_id: 1,
    observacoes: "Dia de descanso, totalmente recuperado",
  },
]

export const mockFeedbacks = [
  {
    id: 1,
    mensagem: "Treino muito intenso hoje, senti dificuldade nos últimos exercícios",
    data: "2025-01-20T15:30:00Z",
    atleta_id: 1,
    atleta_nome: "João Silva",
    treinador_id: 2,
    lido: false,
    esr_valor: 4,
  },
  {
    id: 2,
    mensagem: "Excelente recuperação! Pronto para aumentar a carga",
    data: "2025-01-19T09:00:00Z",
    atleta_id: 1,
    atleta_nome: "João Silva",
    treinador_id: 2,
    lido: true,
    esr_valor: 8,
  },
  {
    id: 3,
    mensagem: "Sentindo dor no joelho direito, preciso de orientação",
    data: "2025-01-18T16:45:00Z",
    atleta_id: 3,
    atleta_nome: "Ana Costa",
    treinador_id: 2,
    lido: false,
    esr_valor: 5,
  },
  {
    id: 4,
    mensagem: "Consegui completar todas as séries hoje, me sinto mais forte!",
    data: "2025-01-17T14:20:00Z",
    atleta_id: 4,
    atleta_nome: "Pedro Oliveira",
    treinador_id: 2,
    lido: true,
    esr_valor: 7,
  },
]

export const mockAvaliacoesFisicas = [
  {
    id: 1,
    data: "2025-01-15T10:00:00Z",
    frequencia_cardiaca: 60,
    observacoes: "Atleta em boa forma, pronto para iniciar ciclo de força",
    zona_treinamento: "Zona 3-4",
    atleta_id: 1,
    treinador_id: 2,
    zonas_calculadas: {
      zona1: { min: 114, max: 133, nome: "Recuperação" },
      zona2: { min: 133, max: 152, nome: "Aeróbica" },
      zona3: { min: 152, max: 171, nome: "Tempo" },
      zona4: { min: 171, max: 190, nome: "Anaeróbica" },
      zona5: { min: 190, max: 209, nome: "VO2 Max" },
    },
  },
]

export const mockHistoryData = {
  weekData: [
    { day: "Seg", esr: 7, zone: "Zona 3", date: "2025-01-20" },
    { day: "Ter", esr: 5, zone: "Zona 4", date: "2025-01-21" },
    { day: "Qua", esr: 8, zone: "Zona 2", date: "2025-01-22" },
    { day: "Qui", esr: 6, zone: "Zona 3", date: "2025-01-23" },
    { day: "Sex", esr: 4, zone: "Zona 4", date: "2025-01-24" },
    { day: "Sáb", esr: 9, zone: "Zona 1", date: "2025-01-25" },
    { day: "Dom", esr: 10, zone: "Descanso", date: "2025-01-26" },
  ],
  stats: {
    esrMedio: 6.7,
    totalTreinos: 5,
    tempoTotal: "3.5h",
    melhorESR: 10,
    piorESR: 4,
  },
}

export const mockAthleteStats = {
  1: {
    weeklySessionsCompleted: 3,
    weeklySessionsTotal: 5,
    totalLoad: 245,
    streak: 7,
    totalMinutes: 285,
    weeklyProgress: {
      completed: 3,
      total: 5,
      percentage: 60,
      nextSession: "Amanhã às 09:00",
    },
  },
}
